export let animalEmojis = [
    {
        "codes": "1F435",
        "char": "🐵",
        "name": "monkey face",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "monkey"
    },
    {
        "codes": "1F412",
        "char": "🐒",
        "name": "monkey",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "monkey"
    },
    {
        "codes": "1F98D",
        "char": "🦍",
        "name": "gorilla",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "gorilla"
    },
    {
        "codes": "1F9A7",
        "char": "🦧",
        "name": "orangutan",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "gorilla"
    },
    {
        "codes": "1F436",
        "char": "🐶",
        "name": "dog face",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "dog"
    },
    {
        "codes": "1F415",
        "char": "🐕",
        "name": "dog",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "dog"
    },
    {
        "codes": "1F9AE",
        "char": "🦮",
        "name": "guide dog",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "dog"
    },
    {
        "codes": "1F415 200D 1F9BA",
        "char": "🐕‍🦺",
        "name": "service dog",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "dog"
    },
    {
        "codes": "1F429",
        "char": "🐩",
        "name": "poodle",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F43A",
        "char": "🐺",
        "name": "wolf",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F98A",
        "char": "🦊",
        "name": "fox",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F99D",
        "char": "🦝",
        "name": "raccoon",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F431",
        "char": "🐱",
        "name": "cat face",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "cat"
    },
    {
        "codes": "1F408",
        "char": "🐈",
        "name": "cat",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "cat"
    },
    {
        "codes": "1F981",
        "char": "🦁",
        "name": "lion",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F42F",
        "char": "🐯",
        "name": "tiger face",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "tiger"
    },
    {
        "codes": "1F405",
        "char": "🐅",
        "name": "tiger",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "tiger"
    },
    {
        "codes": "1F406",
        "char": "🐆",
        "name": "leopard",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F434",
        "char": "🐴",
        "name": "horse face",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "horse"
    },
    {
        "codes": "1F40E",
        "char": "🐎",
        "name": "horse",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "horse"
    },
    {
        "codes": "1F984",
        "char": "🦄",
        "name": "unicorn",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F993",
        "char": "🦓",
        "name": "zebra",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F98C",
        "char": "🦌",
        "name": "deer",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F42E",
        "char": "🐮",
        "name": "cow face",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "cow"
    },
    {
        "codes": "1F402",
        "char": "🐂",
        "name": "ox",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F403",
        "char": "🐃",
        "name": "water buffalo",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F404",
        "char": "🐄",
        "name": "cow",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "cow"
    },
    {
        "codes": "1F437",
        "char": "🐷",
        "name": "pig face",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "pig"
    },
    {
        "codes": "1F416",
        "char": "🐖",
        "name": "pig",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "pig"
    },
    {
        "codes": "1F417",
        "char": "🐗",
        "name": "boar",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F43D",
        "char": "🐽",
        "name": "pig nose",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "pig"
    },
    {
        "codes": "1F40F",
        "char": "🐏",
        "name": "ram",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "sheep"
    },
    {
        "codes": "1F411",
        "char": "🐑",
        "name": "ewe",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "sheep"
    },
    {
        "codes": "1F410",
        "char": "🐐",
        "name": "goat",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F42A",
        "char": "🐪",
        "name": "camel",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "camel"
    },
    {
        "codes": "1F42B",
        "char": "🐫",
        "name": "two-hump camel",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "camel"
    },
    {
        "codes": "1F999",
        "char": "🦙",
        "name": "llama",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F992",
        "char": "🦒",
        "name": "giraffe",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F418",
        "char": "🐘",
        "name": "elephant",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F98F",
        "char": "🦏",
        "name": "rhinoceros",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F99B",
        "char": "🦛",
        "name": "hippopotamus",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F42D",
        "char": "🐭",
        "name": "mouse face",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "mouse"
    },
    {
        "codes": "1F401",
        "char": "🐁",
        "name": "mouse",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "mouse"
    },
    {
        "codes": "1F400",
        "char": "🐀",
        "name": "rat",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "rat"
    },
    {
        "codes": "1F439",
        "char": "🐹",
        "name": "hamster",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F430",
        "char": "🐰",
        "name": "rabbit face",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "rabbit"
    },
    {
        "codes": "1F407",
        "char": "🐇",
        "name": "rabbit",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "rabbit"
    },
    {
        "codes": "1F43F FE0F",
        "char": "🐿️",
        "name": "chipmunk",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F43F",
        "char": "🐿",
        "name": "chipmunk",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F994",
        "char": "🦔",
        "name": "hedgehog",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F987",
        "char": "🦇",
        "name": "bat",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F43B",
        "char": "🐻",
        "name": "bear",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "bear"
    },
    {
        "codes": "1F43B 200D 2744 FE0F",
        "char": "🐻‍❄️",
        "name": "polar bear",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "bear"
    },
    {
        "codes": "1F428",
        "char": "🐨",
        "name": "koala",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "panda"
    },
    {
        "codes": "1F43C",
        "char": "🐼",
        "name": "panda",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "panda"
    },
    {
        "codes": "1F9A5",
        "char": "🦥",
        "name": "sloth",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F9A6",
        "char": "🦦",
        "name": "otter",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F9A8",
        "char": "🦨",
        "name": "skunk",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F998",
        "char": "🦘",
        "name": "kangaroo",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F9A1",
        "char": "🦡",
        "name": "badger",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false,
        "uniqueName": "rat"
    },
    {
        "codes": "1F43E",
        "char": "🐾",
        "name": "paw prints",
        "category": "Animals & Nature (animal-mammal)",
        "group": "Animals & Nature",
        "subgroup": "animal-mammal",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F983",
        "char": "🦃",
        "name": "turkey",
        "category": "Animals & Nature (animal-bird)",
        "group": "Animals & Nature",
        "subgroup": "animal-bird",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F414",
        "char": "🐔",
        "name": "chicken",
        "category": "Animals & Nature (animal-bird)",
        "group": "Animals & Nature",
        "subgroup": "animal-bird",
        "clicked": false,
        "displayed": false,
        "uniqueName": "chicken"
    },
    {
        "codes": "1F413",
        "char": "🐓",
        "name": "rooster",
        "category": "Animals & Nature (animal-bird)",
        "group": "Animals & Nature",
        "subgroup": "animal-bird",
        "clicked": false,
        "displayed": false,
        "uniqueName": "chicken"
    },
    {
        "codes": "1F423",
        "char": "🐣",
        "name": "hatching chick",
        "category": "Animals & Nature (animal-bird)",
        "group": "Animals & Nature",
        "subgroup": "animal-bird",
        "clicked": false,
        "displayed": false,
        "uniqueName": "chick"
    },
    {
        "codes": "1F424",
        "char": "🐤",
        "name": "baby chick",
        "category": "Animals & Nature (animal-bird)",
        "group": "Animals & Nature",
        "subgroup": "animal-bird",
        "clicked": false,
        "displayed": false,
        "uniqueName": "chick"
    },
    {
        "codes": "1F425",
        "char": "🐥",
        "name": "front-facing baby chick",
        "category": "Animals & Nature (animal-bird)",
        "group": "Animals & Nature",
        "subgroup": "animal-bird",
        "clicked": false,
        "displayed": false,
        "uniqueName": "chick"
    },
    {
        "codes": "1F426",
        "char": "🐦",
        "name": "bird",
        "category": "Animals & Nature (animal-bird)",
        "group": "Animals & Nature",
        "subgroup": "animal-bird",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F427",
        "char": "🐧",
        "name": "penguin",
        "category": "Animals & Nature (animal-bird)",
        "group": "Animals & Nature",
        "subgroup": "animal-bird",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F54A FE0F",
        "char": "🕊️",
        "name": "dove",
        "category": "Animals & Nature (animal-bird)",
        "group": "Animals & Nature",
        "subgroup": "animal-bird",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F985",
        "char": "🦅",
        "name": "eagle",
        "category": "Animals & Nature (animal-bird)",
        "group": "Animals & Nature",
        "subgroup": "animal-bird",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F986",
        "char": "🦆",
        "name": "duck",
        "category": "Animals & Nature (animal-bird)",
        "group": "Animals & Nature",
        "subgroup": "animal-bird",
        "clicked": false,
        "displayed": false,
        "uniqueName": "duckSwan"
    },
    {
        "codes": "1F9A2",
        "char": "🦢",
        "name": "swan",
        "category": "Animals & Nature (animal-bird)",
        "group": "Animals & Nature",
        "subgroup": "animal-bird",
        "clicked": false,
        "displayed": false,
        "uniqueName": "duckSwan"
    },
    {
        "codes": "1F989",
        "char": "🦉",
        "name": "owl",
        "category": "Animals & Nature (animal-bird)",
        "group": "Animals & Nature",
        "subgroup": "animal-bird",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F9A9",
        "char": "🦩",
        "name": "flamingo",
        "category": "Animals & Nature (animal-bird)",
        "group": "Animals & Nature",
        "subgroup": "animal-bird",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F99A",
        "char": "🦚",
        "name": "peacock",
        "category": "Animals & Nature (animal-bird)",
        "group": "Animals & Nature",
        "subgroup": "animal-bird",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F99C",
        "char": "🦜",
        "name": "parrot",
        "category": "Animals & Nature (animal-bird)",
        "group": "Animals & Nature",
        "subgroup": "animal-bird",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F438",
        "char": "🐸",
        "name": "frog",
        "category": "Animals & Nature (animal-amphibian)",
        "group": "Animals & Nature",
        "subgroup": "animal-amphibian",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F40A",
        "char": "🐊",
        "name": "crocodile",
        "category": "Animals & Nature (animal-reptile)",
        "group": "Animals & Nature",
        "subgroup": "animal-reptile",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F422",
        "char": "🐢",
        "name": "turtle",
        "category": "Animals & Nature (animal-reptile)",
        "group": "Animals & Nature",
        "subgroup": "animal-reptile",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F98E",
        "char": "🦎",
        "name": "lizard",
        "category": "Animals & Nature (animal-reptile)",
        "group": "Animals & Nature",
        "subgroup": "animal-reptile",
        "clicked": false,
        "displayed": false,
        "uniqueName": "reptile"
    },
    {
        "codes": "1F40D",
        "char": "🐍",
        "name": "snake",
        "category": "Animals & Nature (animal-reptile)",
        "group": "Animals & Nature",
        "subgroup": "animal-reptile",
        "clicked": false,
        "displayed": false,
        "uniqueName": "reptile"
    },
    {
        "codes": "1F432",
        "char": "🐲",
        "name": "dragon face",
        "category": "Animals & Nature (animal-reptile)",
        "group": "Animals & Nature",
        "subgroup": "animal-reptile",
        "clicked": false,
        "displayed": false,
        "uniqueName": "dragon"
    },
    {
        "codes": "1F409",
        "char": "🐉",
        "name": "dragon",
        "category": "Animals & Nature (animal-reptile)",
        "group": "Animals & Nature",
        "subgroup": "animal-reptile",
        "clicked": false,
        "displayed": false,
        "uniqueName": "dragon"
    },
    {
        "codes": "1F995",
        "char": "🦕",
        "name": "sauropod",
        "category": "Animals & Nature (animal-reptile)",
        "group": "Animals & Nature",
        "subgroup": "animal-reptile",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F996",
        "char": "🦖",
        "name": "T-Rex",
        "category": "Animals & Nature (animal-reptile)",
        "group": "Animals & Nature",
        "subgroup": "animal-reptile",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F433",
        "char": "🐳",
        "name": "spouting whale",
        "category": "Animals & Nature (animal-marine)",
        "group": "Animals & Nature",
        "subgroup": "animal-marine",
        "clicked": false,
        "displayed": false,
        "uniqueName": "whale"
    },
    {
        "codes": "1F40B",
        "char": "🐋",
        "name": "whale",
        "category": "Animals & Nature (animal-marine)",
        "group": "Animals & Nature",
        "subgroup": "animal-marine",
        "clicked": false,
        "displayed": false,
        "uniqueName": "whale"
    },
    {
        "codes": "1F42C",
        "char": "🐬",
        "name": "dolphin",
        "category": "Animals & Nature (animal-marine)",
        "group": "Animals & Nature",
        "subgroup": "animal-marine",
        "clicked": false,
        "displayed": false,
        "uniqueName": "dolShark"
    },
    {
        "codes": "1F41F",
        "char": "🐟",
        "name": "fish",
        "category": "Animals & Nature (animal-marine)",
        "group": "Animals & Nature",
        "subgroup": "animal-marine",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F420",
        "char": "🐠",
        "name": "tropical fish",
        "category": "Animals & Nature (animal-marine)",
        "group": "Animals & Nature",
        "subgroup": "animal-marine",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F421",
        "char": "🐡",
        "name": "blowfish",
        "category": "Animals & Nature (animal-marine)",
        "group": "Animals & Nature",
        "subgroup": "animal-marine",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F988",
        "char": "🦈",
        "name": "shark",
        "category": "Animals & Nature (animal-marine)",
        "group": "Animals & Nature",
        "subgroup": "animal-marine",
        "clicked": false,
        "displayed": false,
        "uniqueName": "dolShark"
    },
    {
        "codes": "1F419",
        "char": "🐙",
        "name": "octopus",
        "category": "Animals & Nature (animal-marine)",
        "group": "Animals & Nature",
        "subgroup": "animal-marine",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F41A",
        "char": "🐚",
        "name": "spiral shell",
        "category": "Animals & Nature (animal-marine)",
        "group": "Animals & Nature",
        "subgroup": "animal-marine",
        "clicked": false,
        "displayed": false,
        "uniqueName": "shells"
    },
    {
        "codes": "1F40C",
        "char": "🐌",
        "name": "snail",
        "category": "Animals & Nature (animal-bug)",
        "group": "Animals & Nature",
        "subgroup": "animal-bug",
        "clicked": false,
        "displayed": false,
        "uniqueName": "shells"
    },
    {
        "codes": "1F98B",
        "char": "🦋",
        "name": "butterfly",
        "category": "Animals & Nature (animal-bug)",
        "group": "Animals & Nature",
        "subgroup": "animal-bug",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F41B",
        "char": "🐛",
        "name": "bug",
        "category": "Animals & Nature (animal-bug)",
        "group": "Animals & Nature",
        "subgroup": "animal-bug",
        "clicked": false,
        "displayed": false,
        "uniqueName": "maggAnt"
    },
    {
        "codes": "1F41C",
        "char": "🐜",
        "name": "ant",
        "category": "Animals & Nature (animal-bug)",
        "group": "Animals & Nature",
        "subgroup": "animal-bug",
        "clicked": false,
        "displayed": false,
        "uniqueName": "maggAnt"
    },
    {
        "codes": "1F41D",
        "char": "🐝",
        "name": "honeybee",
        "category": "Animals & Nature (animal-bug)",
        "group": "Animals & Nature",
        "subgroup": "animal-bug",
        "clicked": false,
        "displayed": false,
        "uniqueName": "flyingInsects"
    },
    {
        "codes": "1F41E",
        "char": "🐞",
        "name": "lady beetle",
        "category": "Animals & Nature (animal-bug)",
        "group": "Animals & Nature",
        "subgroup": "animal-bug",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F997",
        "char": "🦗",
        "name": "cricket",
        "category": "Animals & Nature (animal-bug)",
        "group": "Animals & Nature",
        "subgroup": "animal-bug",
        "clicked": false,
        "displayed": false,
        "uniqueName": "flyingInsects"
    },
    {
        "codes": "1F577 FE0F",
        "char": "🕷️",
        "name": "spider",
        "category": "Animals & Nature (animal-bug)",
        "group": "Animals & Nature",
        "subgroup": "animal-bug",
        "clicked": false,
        "displayed": false,
        "uniqueName": "spider"
    },
    {
        "codes": "1F577",
        "char": "🕷",
        "name": "spider",
        "category": "Animals & Nature (animal-bug)",
        "group": "Animals & Nature",
        "subgroup": "animal-bug",
        "clicked": false,
        "displayed": false,
        "uniqueName": "spider"
    },
    {
        "codes": "1F578 FE0F",
        "char": "🕸️",
        "name": "spider web",
        "category": "Animals & Nature (animal-bug)",
        "group": "Animals & Nature",
        "subgroup": "animal-bug",
        "clicked": false,
        "displayed": false,
        "uniqueName": "spiderWeb"
    },
    {
        "codes": "1F578",
        "char": "🕸",
        "name": "spider web",
        "category": "Animals & Nature (animal-bug)",
        "group": "Animals & Nature",
        "subgroup": "animal-bug",
        "clicked": false,
        "displayed": false,
        "uniqueName": "spiderWeb"
    },
    {
        "codes": "1F982",
        "char": "🦂",
        "name": "scorpion",
        "category": "Animals & Nature (animal-bug)",
        "group": "Animals & Nature",
        "subgroup": "animal-bug",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F99F",
        "char": "🦟",
        "name": "mosquito",
        "category": "Animals & Nature (animal-bug)",
        "group": "Animals & Nature",
        "subgroup": "animal-bug",
        "clicked": false,
        "displayed": false
    },
    {
        "codes": "1F9A0",
        "char": "🦠",
        "name": "microbe",
        "category": "Animals & Nature (animal-bug)",
        "group": "Animals & Nature",
        "subgroup": "animal-bug",
        "clicked": false,
        "displayed": false
    }
]